### ISSUE TITLE
Is there any plan/way in UI Router to support Angular,AngularJS,React together in a SPA

### ISSUE THREAD

**Issue by tejaswiniKanigolla** [ui-router/react-hybrid#350] opened 2019-11-22 13:57 UTC
My Project is a UX Platform (a SPA), where we have experiences rendered in AngularJs ,Angular. We are currently using uirouter/angular-hybrid for managing the states in our application.   Now, we also want to support react experiences in our platform.  Today there is no out of box support from uirouter -which works for AngulrJS,Angular and React together. With this context set, I  would like to know some inputs on below questions in specific.

1. Is there any plan to support all 3 Frameworks in single ui router package?
2. Are there any alternative suggestions/methods to have common routing for all 3 Frameworks?

**Comment by christopherthielen** [comment] 2020-02-05 03:26
dupe of https://github.com/ui-router/angular-hybrid/issues/378

I am experimenting with making the framework specific code easier to mix in to a core ui-router, but I'm still early in the process.

**Closed by christopherthielen** 2020-02-05 03:27 UTC
